language: python
sudo: false

addons:
  apt:
    packages:
    - tidy

python:
 - 3.6

script:
 - tidy -errors -quiet html/index.html

jobs:
  include:
    - stage: deploy
      if: branch = master and type = push
      install:
      script:
      - docker build
            --file "Dockerfile"
            --tag "brianmay/linuxpenguins.xyz:latest"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "brianmay/linuxpenguins.xyz:latest"
