apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-24T04:43:49Z"
  generation: 1
  labels:
    app: linuxpenguins
  name: linuxpenguins
  namespace: default
  resourceVersion: "21688"
  selfLink: /apis/apps/v1/namespaces/default/deployments/linuxpenguins
  uid: 0d142800-4c14-444a-802b-1640a4911429
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: linuxpenguins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linuxpenguins
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        name: github-brianmay-linuxpenguins-xyz-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
