version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout # check out the code in the project directory
      - run: |
          gem install bundler
          bundle install
          bundle exec htmlproofer html --disable-external

  deploy-prod:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker
      - run: |
          docker build \
            --file "Dockerfile" \
            --tag "brianmay/linuxpenguins.xyz:latest" \
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg "VCS_REF=$CIRCLE_SHA1" \
            .
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          docker push "brianmay/linuxpenguins.xyz:latest"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          context: Docker
          requires:
            - build
          filters:
            branches:
              only: master
