name: Build and Deploy to Docker Hub

on: [push, pull_request]

jobs:
  test:
    name: Test valid HTML
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 

    - name: Install Ruby Packages
      run: |-
        gem install bundler
        bundle install

    - name: Test Result
      run: |-
        bundle exec htmlproofer html --disable-external
