name: Build and Deploy to Docker Hub

on: [push, pull_request]

jobs:
  test:
    name: Test valid HTML
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Install Ruby Packages
      run: |-
        gem install bundler
        bundle install

    - name: Test Result
      run: |-
        bundle exec htmlproofer html --disable-external

  push:
    name: Push
    uses: brianmay/workflows/.github/workflows/docker.yaml@b8ac8e58821a896616de972c4e8602c3e17a6a46
    secrets:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
    needs:
      - test
